// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpelVagtplan.Data;

#nullable disable

namespace SimpelVagtplan.Migrations
{
    [DbContext(typeof(SimpelVagtplanContext))]
    [Migration("20221013142910_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SimpelVagtplan.Models.Medarbejder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medarbejder");
                });

            modelBuilder.Entity("SimpelVagtplan.Models.Opgave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("vagtId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("vagtId");

                    b.ToTable("Opgave");
                });

            modelBuilder.Entity("SimpelVagtplan.Models.Vagt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedarbejderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MedarbejderId");

                    b.ToTable("Vagt");
                });

            modelBuilder.Entity("SimpelVagtplan.Models.Opgave", b =>
                {
                    b.HasOne("SimpelVagtplan.Models.Vagt", "vagt")
                        .WithMany()
                        .HasForeignKey("vagtId");

                    b.Navigation("vagt");
                });

            modelBuilder.Entity("SimpelVagtplan.Models.Vagt", b =>
                {
                    b.HasOne("SimpelVagtplan.Models.Medarbejder", "Medarbejder")
                        .WithMany()
                        .HasForeignKey("MedarbejderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medarbejder");
                });
#pragma warning restore 612, 618
        }
    }
}
